### ISSUE TITLE
Do you have arm64 version ? 

### ISSUE THREAD

**Issue by sanfx** [timoa/app-stores-prometheus-exporter#13]
I am getting this error, no matter what node alpine version I tried I did not get any success.

```
$ sudo docker-compose up 
Creating appstoresprometheusexporter_api_1 ... 
Creating appstoresprometheusexporter_api_1 ... done
Attaching to appstoresprometheusexporter_api_1
api_1  | standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by timoa** [comment]
Hi @sanfx!

I will have a look since the Docker image is supposed to be used on most of the architectures.

Can you, please, provide more information about your OS version?

Thanks to having created an issue :)

**Comment by timoa** [comment]
Hi @sanfx ,

I will add support for arm64 and other architectures that I can build with the GitHub Actions Runners and let you know when it's available.

I have updated the project with the latest Node 16.x, deps security, and added new metrics. 
The next step will be to improve the Docker compatibility. Thanks again for your message and I hope you still using this project 👍
