### ISSUE TITLE
App download counts

### ISSUE THREAD

**Issue by beingyash** [timoa/app-stores-prometheus-exporter#14]
Can we also make available the app download counts if possible?

**Comment by timoa** [comment]
Hi @beingyash!

Thanks for your contribution :)

I will have a look but I'm relying on two libraries to get the data (scrappers) and I need to see if there is any new data but I don't think that we can get the precise number of downloads but something like "14K".

I will update this issue when I will have more information.

Thanks again!

**Comment by timoa** [comment]
There is no count of downloads but the number of installs on Google Play.

I added the minimum and maximum installs since the launch of an app for Google Play and looking to get that for the App Store.
