### ISSUE TITLE
docker image is outdated

### ISSUE THREAD

**Issue by vzhgit** [timoa/app-stores-prometheus-exporter#31]
Hi. 

Can you trigger a new build of your docker image to build it with the latest version of facundoolano/google-play-scraper?

I have a similar [error ](https://github.com/facundoolano/google-play-scraper/issues/480) in a docker log of container and an application doesn't work:
```
1a7e9cf0-19f5-11ec-bf0e-b3798ae748b6 | 2021-09-22 04:18:48 | error: Google Play Scraper error for the app "<my app>"" (it): Cannot read property 'replace' of undefined

**Comment by rflume** [comment]
You can build your own image in the meantime.
Update the "google-play-scraper": "^8.0.2" dependency to "^8.0.4" and build the Docker image from the Dockerfile included in the repo.
This fixed the issue for me.

**Comment by timoa** [comment]
Hi @vzhgit / @rflume ,

Thanks, for your messages.

I restarted working on this project a few days ago, and it using now the latest versions of Google Play and App Store scrapers.

I added new metrics, and I will continue to add the ones that can be relevant + update the Grafana dashboards.

Thanks again!
