### ISSUE TITLE
Error while accessing through browser

### ISSUE THREAD

**Issue by sagiR456** [timoa/app-stores-prometheus-exporter#4]
Full Stack Trace: 
Prometheus App Stores Exporter is listening on http://localhost:9514
_http_outgoing.js:747
      throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'first argument',
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer
    at ServerResponse.end (_http_outgoing.js:747:13)
    at Server.server.on (/opt/app/src/exporter.js:63:14)
    at Server.emit (events.js:180:13)
    at parserOnIncoming (_http_server.js:642:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-stores-prometheus-exporter@0.2.0 start: `node src/exporter`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-stores-prometheus-exporter@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app-user/.npm/_logs/2019-07-16T08_13_35_586Z-debug.log

**Comment by sagiR456** [comment]
Full stack trace:
Prometheus App Stores Exporter is listening on http://localhost:9514
_http_outgoing.js:747
      throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'first argument',
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer
    at ServerResponse.end (_http_outgoing.js:747:13)
    at Server.server.on (/opt/app/src/exporter.js:63:14)
    at Server.emit (events.js:180:13)
    at parserOnIncoming (_http_server.js:642:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-stores-prometheus-exporter@0.2.0 start: `node src/exporter`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-stores-prometheus-exporter@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app-user/.npm/_logs/2019-07-16T08_13_35_586Z-debug.log

**Comment by timoa** [comment]
Thanks @sagiR456! I haven’t seen this issue with the current Docker image and it’s fixed.

A new Docker image has been deployed with up to date dependencies.

I will add the unit-tests and Grafana dashboards tomorrow.
