### ISSUE TITLE
Health Endpoint (GET)

### ISSUE THREAD

**Issue by raynigon** [timoa/app-stores-prometheus-exporter#97]
It would be nice to have an health endpoint to check if the exporter is up and running.
Currently there seems to be an HealthCheck which is only available for HEAD requests.
Since the [K8s httpGet probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes)  needs an endpoint which responds to get requests it would be nice to have such an endpoint available at `/health`.

It would be nice to document this endpoint in the Readme.md

**Comment by lehha** [comment]
Hi! After this update, a Docker HEALTHCHECK came broken.

`npm run docker:status`

shows

`STATUS: 404`

src/healthcheck.js use URI /_health
but change to /health didn't help
